import type { CarouselTheme, CarouselType } from '@/types'

export const CAROUSEL_TYPES: CarouselType[] = [
  {
    id: 'how_to_guide',
    label: 'How-To Guide',
    description: 'Step-by-step process to achieve an outcome',
    best_for: 'Tutorials, frameworks, processes',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'free',
    icon: 'BookOpen',
    example_title: 'How to close enterprise deals in 5 steps',
  },
  {
    id: 'listicle',
    label: 'The Listicle',
    description: 'Numbered list of insights, tools, or lessons',
    best_for: 'Resource lists, recommendations, quick wins',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'free',
    icon: 'List',
    example_title: '7 tools every founder needs in 2025',
  },
  {
    id: 'myth_buster',
    label: 'Myth Buster',
    description: 'Challenge conventional wisdom with evidence',
    best_for: 'Authority building, contrarian takes',
    slide_structure: ['title','content','content','content','content','cta'],
    plan_required: 'free',
    icon: 'ShieldOff',
    example_title: '5 myths about LinkedIn growth that are wrong',
  },
  {
    id: 'lessons_learned',
    label: 'Lessons Learned',
    description: 'Retrospective insights from experience',
    best_for: 'Personal stories, career milestones',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'free',
    icon: 'Lightbulb',
    example_title: '8 lessons from my first year as a founder',
  },
  {
    id: 'beginners_guide',
    label: "Beginner's Guide",
    description: 'Everything a newcomer needs to know',
    best_for: 'Educational content, onboarding audiences',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'free',
    icon: 'GraduationCap',
    example_title: 'Everything a new sales rep needs to know',
  },
  {
    id: 'tools_resources',
    label: 'Tools and Resources',
    description: 'Curated list of tools with brief descriptions',
    best_for: 'High-save content, resource sharing',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'free',
    icon: 'Wrench',
    example_title: '6 free tools that replace expensive software',
  },
  {
    id: 'case_study',
    label: 'Case Study',
    description: 'From problem to result — the full story',
    best_for: 'B2B lead gen, client wins, social proof',
    slide_structure: ['title','content','content','content','content','content','content','cta'],
    plan_required: 'starter',
    icon: 'TrendingUp',
    example_title: 'How we grew from 0 to 10,000 followers in 90 days',
  },
  {
    id: 'framework',
    label: 'The Framework',
    description: 'A named system or methodology you use',
    best_for: 'Thought leadership, methodology sharing',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'starter',
    icon: 'Layout',
    example_title: 'The 4-part framework I use for every client pitch',
  },
  {
    id: 'story_arc',
    label: 'Story Arc',
    description: 'Personal narrative from struggle to success',
    best_for: 'Personal branding, emotional connection',
    slide_structure: ['title','content','content','content','content','content','content','cta'],
    plan_required: 'starter',
    icon: 'BookMarked',
    example_title: 'The story of how I built a company from my bedroom',
  },
  {
    id: 'before_after',
    label: 'Before and After',
    description: 'Transformation through contrast',
    best_for: 'Strategy changes, career pivots, redesigns',
    slide_structure: ['title','content','content','content','content','cta'],
    plan_required: 'starter',
    icon: 'ArrowRightLeft',
    example_title: 'Before vs after I fixed my LinkedIn profile',
  },
  {
    id: 'comparison',
    label: 'The Comparison',
    description: 'Side-by-side breakdown of two approaches',
    best_for: 'Decision-making content, debate-sparking',
    slide_structure: ['title','content','content','content','content','cta'],
    plan_required: 'starter',
    icon: 'Columns',
    example_title: 'Bootstrapping vs VC funding — the honest comparison',
  },
  {
    id: 'career_advice',
    label: 'Career Advice',
    description: 'What you wish someone told you earlier',
    best_for: 'Career changers, job seekers, mentorship content',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'starter',
    icon: 'Compass',
    example_title: 'What I wish someone told me at 25 about my career',
  },
  {
    id: 'data_breakdown',
    label: 'Data Breakdown',
    description: 'Statistics and research made visual',
    best_for: 'Authority building, research sharing',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'starter',
    icon: 'BarChart2',
    example_title: '7 LinkedIn statistics that will change your strategy',
  },
  {
    id: 'timeline_journey',
    label: 'Timeline and Journey',
    description: 'Chronological story of building or growing',
    best_for: 'Founders, builders, long-term projects',
    slide_structure: ['title','content','content','content','content','content','content','cta'],
    plan_required: 'starter',
    icon: 'Calendar',
    example_title: 'Month by month: how I scaled to 1 crore revenue',
  },
  {
    id: 'predictions_trends',
    label: 'Predictions and Trends',
    description: 'Forward-looking industry forecast',
    best_for: 'Thought leadership, getting cited and shared',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'pro',
    icon: 'Telescope',
    example_title: '5 trends that will reshape Indian SaaS by 2026',
  },
  {
    id: 'hiring_post',
    label: 'Hiring Post',
    description: 'Attract talent while building employer brand',
    best_for: 'Founders, HR leaders, team builders',
    slide_structure: ['title','content','content','content','content','cta'],
    plan_required: 'pro',
    icon: 'Users',
    example_title: 'Why joining our team is different from what you heard',
  },
  {
    id: 'book_summary',
    label: 'Book and Podcast Summary',
    description: 'Key ideas from a book or podcast',
    best_for: 'High-save content, positioning as well-read',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'pro',
    icon: 'Headphones',
    example_title: '6 ideas from Zero to One that changed how I build',
  },
  {
    id: 'behind_the_scenes',
    label: 'Behind The Scenes',
    description: 'The unseen process behind visible results',
    best_for: 'Transparency content, trust building',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'pro',
    icon: 'Eye',
    example_title: 'What building a 10 crore business actually looks like',
  },
  {
    id: 'mistakes_breakdown',
    label: 'Mistakes Breakdown',
    description: 'Honest breakdown of costly errors',
    best_for: 'Vulnerability plus practical lessons',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'pro',
    icon: 'AlertTriangle',
    example_title: '5 hiring mistakes that cost me 30 lakhs',
  },
  {
    id: 'industry_insider',
    label: 'Industry Insider',
    description: 'Privileged knowledge most people do not share',
    best_for: 'Niche authority, insider positioning',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'pro',
    icon: 'Unlock',
    example_title: 'What top VCs look at that nobody talks about',
  },
  {
    id: 'research_findings',
    label: 'Research Findings',
    description: 'Insights from studying many cases or data',
    best_for: 'Evidence-based authority, getting cited',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'pro',
    icon: 'Search',
    example_title: 'I studied 50 LinkedIn profiles. Here is what I found.',
  },
  {
    id: 'sales_playbook',
    label: 'Sales Playbook',
    description: 'Exact process for closing deals',
    best_for: 'Sales leaders, revenue teams, SDRs',
    slide_structure: ['title','content','content','content','content','content','content','cta'],
    plan_required: 'pro',
    icon: 'Target',
    example_title: 'The 6-step process I use to close 50 lakh enterprise deals',
  },
  {
    id: 'outreach_template',
    label: 'Cold Outreach Template',
    description: 'Exact messages that get high reply rates',
    best_for: 'Sales, BD, recruiters, job seekers',
    slide_structure: ['title','content','content','content','content','cta'],
    plan_required: 'pro',
    icon: 'Mail',
    example_title: 'The 3-line message that gets a 40 percent reply rate',
  },
  {
    id: 'product_launch',
    label: 'Product and Service Launch',
    description: 'Announce a new offer compellingly',
    best_for: 'Founders, product teams, consultants',
    slide_structure: ['title','content','content','content','content','cta'],
    plan_required: 'pro',
    icon: 'Rocket',
    example_title: 'Introducing PostPika — here is why I built it',
  },
  {
    id: 'event_recap',
    label: 'Event and Conference Recap',
    description: 'Extend the value of attending an event',
    best_for: 'Conference speakers and serious attendees',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'pro',
    icon: 'Mic',
    example_title: '7 things I learned at SaasBoomi that changed my thinking',
  },
  {
    id: 'contrarian_take',
    label: 'Contrarian Take',
    description: 'Why conventional wisdom is completely wrong',
    best_for: 'Bold thinkers, debate-sparking content',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'pro',
    icon: 'Zap',
    example_title: 'Why most LinkedIn advice is making you invisible',
  },
  {
    id: 'day_in_the_life',
    label: 'Day In The Life',
    description: 'Demystify a role or lifestyle',
    best_for: 'Aspiration content, recruiting, humanising brands',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'pro',
    icon: 'Sun',
    example_title: 'What a day as a bootstrapped founder actually looks like',
  },
  {
    id: 'investment_thesis',
    label: 'Investment Thesis',
    description: 'Why you believe in an idea or sector',
    best_for: 'Investors, strategic thinkers, founders',
    slide_structure: ['title','content','content','content','content','content','cta'],
    plan_required: 'pro',
    icon: 'TrendingUp',
    example_title: 'Why I believe Indian B2B SaaS is a once-in-a-decade bet',
  },
]

export const CAROUSEL_THEMES: CarouselTheme[] = [
  {
    id: 'clean_minimal',
    label: 'Clean Minimal',
    description: 'White, professional, universally readable',
    plan_required: 'free',
    background: '#FFFFFF',
    text_color: '#0A2540',
    accent_color: '#1D9E75',
    secondary_text: '#5F5E5A',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'navy_authority',
    label: 'Navy Authority',
    description: 'Deep navy, premium and commanding',
    plan_required: 'free',
    background: '#0A2540',
    text_color: '#FFFFFF',
    accent_color: '#1D9E75',
    secondary_text: 'rgba(255,255,255,0.65)',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'teal_signature',
    label: 'Teal Signature',
    description: 'Bold brand teal, distinctive and confident',
    plan_required: 'free',
    background: '#1D9E75',
    text_color: '#FFFFFF',
    accent_color: '#FAEEDA',
    secondary_text: 'rgba(255,255,255,0.8)',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'warm_amber',
    label: 'Warm Amber',
    description: 'Cream and warm, approachable and human',
    plan_required: 'free',
    background: '#FFF8F0',
    text_color: '#2C2218',
    accent_color: '#BA7517',
    secondary_text: '#7A6650',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'charcoal_sharp',
    label: 'Charcoal Sharp',
    description: 'Dark and modern, design-agency feel',
    plan_required: 'starter',
    background: '#1C1C1E',
    text_color: '#FFFFFF',
    accent_color: '#FF6B6B',
    secondary_text: 'rgba(255,255,255,0.6)',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'bold_purple',
    label: 'Bold Purple',
    description: 'Deep purple, creative and memorable',
    plan_required: 'starter',
    background: '#26215C',
    text_color: '#E8E6FF',
    accent_color: '#7F77DD',
    secondary_text: 'rgba(232,230,255,0.65)',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'rose_gold_luxury',
    label: 'Rose Gold Luxury',
    description: 'Blush and gold, elegant magazine aesthetic',
    plan_required: 'starter',
    background: '#FDF0F0',
    text_color: '#7B2D42',
    accent_color: '#C9A84C',
    secondary_text: '#A05060',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'forest_authority',
    label: 'Forest Authority',
    description: 'Deep green, calm and credible',
    plan_required: 'starter',
    background: '#0D3B1E',
    text_color: '#FFFFFF',
    accent_color: '#9FE1CB',
    secondary_text: 'rgba(255,255,255,0.65)',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'india_saffron',
    label: 'India Saffron',
    description: 'White with saffron accents, culturally resonant',
    plan_required: 'starter',
    background: '#FFFAF5',
    text_color: '#1A0A00',
    accent_color: '#FF6B35',
    secondary_text: '#7A4030',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'monochrome_editorial',
    label: 'Monochrome Editorial',
    description: 'Black and white newspaper editorial aesthetic',
    plan_required: 'starter',
    background: '#F5F0E0',
    text_color: '#000000',
    accent_color: '#8B0000',
    secondary_text: '#444441',
    heading_font_size: 30,
    body_font_size: 15,
  },
  {
    id: 'midnight_galaxy',
    label: 'Midnight Galaxy',
    description: 'Deep blue-black with electric blue, futuristic',
    plan_required: 'pro',
    background: '#080C14',
    text_color: '#FFFFFF',
    accent_color: '#4FC3F7',
    secondary_text: 'rgba(255,255,255,0.6)',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'sunset_gradient',
    label: 'Sunset Gradient',
    description: 'Orange to purple, no other carousel looks like this',
    plan_required: 'pro',
    background: '#FF6B35',
    text_color: '#FFFFFF',
    accent_color: '#FAEEDA',
    secondary_text: 'rgba(255,255,255,0.8)',
    heading_font_size: 28,
    body_font_size: 16,
    preview_gradient: ['#FF6B35', '#E8537A', '#534AB7'],
  },
  {
    id: 'botanical_lush',
    label: 'Botanical Lush',
    description: 'Deep green and gold, premium and organic',
    plan_required: 'pro',
    background: '#1B4332',
    text_color: '#F5F0E8',
    accent_color: '#D4AF37',
    secondary_text: 'rgba(245,240,232,0.7)',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'neon_dark',
    label: 'Neon Dark',
    description: 'Pure black with neon green, stops every scroll',
    plan_required: 'pro',
    background: '#0D0D0D',
    text_color: '#FFFFFF',
    accent_color: '#00FF88',
    secondary_text: 'rgba(255,255,255,0.6)',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'ice_corporate',
    label: 'Ice Corporate',
    description: 'Light blue-grey, McKinsey slide deck precision',
    plan_required: 'pro',
    background: '#EBF4FB',
    text_color: '#0A2540',
    accent_color: '#185FA5',
    secondary_text: '#444876',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'terracotta_warm',
    label: 'Terracotta Warm',
    description: 'Rich clay tones, handcrafted and distinctive',
    plan_required: 'pro',
    background: '#C2714F',
    text_color: '#FFFFFF',
    accent_color: '#FFF8F0',
    secondary_text: 'rgba(255,255,255,0.75)',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'luxury_black',
    label: 'Luxury Black',
    description: 'Pure black and gold, screams premium',
    plan_required: 'pro',
    background: '#000000',
    text_color: '#FFFFFF',
    accent_color: '#C9A84C',
    secondary_text: 'rgba(255,255,255,0.6)',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'coral_energy',
    label: 'Coral Energy',
    description: 'Vibrant coral, high energy and youthful',
    plan_required: 'agency',
    background: '#FF6B6B',
    text_color: '#FFFFFF',
    accent_color: '#0A2540',
    secondary_text: 'rgba(255,255,255,0.8)',
    heading_font_size: 28,
    body_font_size: 16,
  },
  {
    id: 'newspaper_broadsheet',
    label: 'Newspaper Broadsheet',
    description: 'Newsprint aesthetic, instantly distinctive',
    plan_required: 'agency',
    background: '#F5F0E0',
    text_color: '#1A1A1A',
    accent_color: '#8B0000',
    secondary_text: '#444441',
    heading_font_size: 30,
    body_font_size: 15,
  },
  {
    id: 'blueprint',
    label: 'Blueprint',
    description: 'Deep blue with grid lines, technical and precise',
    plan_required: 'agency',
    background: '#0A1628',
    text_color: '#FFFFFF',
    accent_color: '#00D4FF',
    secondary_text: 'rgba(255,255,255,0.6)',
    heading_font_size: 28,
    body_font_size: 16,
  },
]

export const CAROUSEL_LIMITS = {
  free:    { carousels_per_month: 2,  max_slides: 5,  pdf_export: false, remove_branding: false, custom_accent: false, font_selection: false },
  starter: { carousels_per_month: 15, max_slides: 8,  pdf_export: true,  remove_branding: true,  custom_accent: false, font_selection: false },
  pro:     { carousels_per_month: -1, max_slides: 10, pdf_export: true,  remove_branding: true,  custom_accent: true,  font_selection: true  },
  agency:  { carousels_per_month: -1, max_slides: 10, pdf_export: true,  remove_branding: true,  custom_accent: true,  font_selection: true  },
}

export const FONT_STYLES = {
  professional: { heading: 'Georgia, serif',                       body: 'system-ui, sans-serif'                },
  modern:       { heading: '"Helvetica Neue", sans-serif',         body: '"Helvetica Neue", sans-serif'         },
  bold:         { heading: 'Impact, "Arial Black", sans-serif',    body: 'Arial, sans-serif'                    },
}

export const ASPECT_RATIOS = {
  square:   { width: 1080, height: 1080, label: 'Square 1:1',   description: 'Safe for all feeds'        },
  portrait: { width: 1080, height: 1350, label: 'Portrait 4:5', description: 'More text space per slide' },
}

export function getThemeById(id: string): CarouselTheme {
  return CAROUSEL_THEMES.find(t => t.id === id) ?? CAROUSEL_THEMES[0]
}

export function getTypeById(id: string): CarouselType | undefined {
  return CAROUSEL_TYPES.find(t => t.id === id)
}

export function getThemesForPlan(plan: string): CarouselTheme[] {
  const order = ['free', 'starter', 'pro', 'agency']
  const planIndex = order.indexOf(plan)
  return CAROUSEL_THEMES.filter(t => order.indexOf(t.plan_required) <= planIndex)
}

export function getTypesForPlan(plan: string): CarouselType[] {
  const order = ['free', 'starter', 'pro', 'agency']
  const planIndex = order.indexOf(plan)
  return CAROUSEL_TYPES.filter(t => order.indexOf(t.plan_required) <= planIndex)
}
