// ─── Hook Styles ──────────────────────────────────────────────────────────────
// 113 hook styles across 6 categories for LinkedIn hook generation

export const HOOK_CATEGORIES = [
  'Curiosity', 'Value', 'Story', 'Engagement', 'Urgency', 'Authority',
] as const

export type HookCategory = typeof HOOK_CATEGORIES[number]

interface HookStyleDef {
  id: string
  label: string
  category: HookCategory
  description: string
  template: string
  example: string
  isPremium: boolean
}

export const HOOK_STYLES: HookStyleDef[] = [

  // ── CURIOSITY (20) ────────────────────────────────────────────────────────

  { id: 'curiosity-gap',      label: 'Curiosity Gap',       category: 'Curiosity',  isPremium: false, description: 'Opens a gap the reader must close',              template: 'The one thing about [X] that nobody tells you...',                               example: 'The one thing about cold outreach that nobody tells you in India...' },
  { id: 'contrarian',         label: 'Contrarian Take',     category: 'Curiosity',  isPremium: false, description: 'Challenges a commonly held belief',              template: '[Popular belief] is wrong. Here is why.',                                        example: 'Posting every day on LinkedIn is wrong. Here is why.' },
  { id: 'myth-bust',          label: 'Myth Buster',         category: 'Curiosity',  isPremium: false, description: 'Debunks a common myth in your niche',            template: 'Myth: [X]. Reality: [Y].',                                                       example: 'Myth: You need 10k followers to get leads. Reality: 200 engaged followers beat 10k passive ones.' },
  { id: 'open-loop',          label: 'Open Loop',           category: 'Curiosity',  isPremium: false, description: 'Starts a story mid-action to create suspense',   template: 'I was [doing X] when [unexpected thing happened].',                              example: 'I was about to close the deal when the client sent one sentence that stopped me cold.' },
  { id: 'counter-intuitive',  label: 'Counter-Intuitive',   category: 'Curiosity',  isPremium: false, description: 'Leads with a surprising reversal of logic',      template: 'The less you [do X], the more [result Y] you get.',                              example: 'The less you post on LinkedIn, the more leads you get. Here is why.' },
  { id: 'forbidden-knowledge',label: 'Forbidden Knowledge', category: 'Curiosity',  isPremium: false, description: 'Teases insider info most people don\'t share',   template: 'Nobody in [industry] talks about this because...',                               example: 'Nobody in Indian SaaS talks about this because it makes the big players uncomfortable.' },
  { id: 'insider-secret',     label: 'Insider Secret',      category: 'Curiosity',  isPremium: false, description: 'Shares what insiders know but outsiders don\'t', template: 'After [X years] in [industry], here is what I know that most don\'t.',          example: 'After 8 years in VC-backed startups, here is what I know that most founders don\'t.' },
  { id: 'pattern-interrupt',  label: 'Pattern Interrupt',   category: 'Curiosity',  isPremium: false, description: 'Breaks expectations with an unexpected opener',  template: 'I used to believe [X]. I was completely wrong.',                                 example: 'I used to believe hustle culture was the answer. I was completely wrong.' },
  { id: 'the-real-reason',    label: 'The Real Reason',     category: 'Curiosity',  isPremium: false, description: 'Exposes the hidden cause behind a known effect', template: 'The real reason [common thing] happens is not what you think.',                  example: 'The real reason most Indian startups fail at Series A is not what the press reports.' },
  { id: 'surprising-data',    label: 'Surprising Data',     category: 'Curiosity',  isPremium: false, description: 'Leads with a stat that defies expectations',     template: '[Surprising %/number] of [group] do [unexpected thing]. Here is why.',         example: '73% of Indian founders who raised a seed round never raised a second. Here is why.' },
  { id: 'what-changed-my-mind',label: 'What Changed My Mind',category: 'Curiosity', isPremium: false, description: 'Documents a belief reversal with evidence',      template: 'I changed my mind about [X]. Here is the moment that did it.',                  example: 'I changed my mind about cold email. Here is the moment that did it.' },
  { id: 'confession',         label: 'Confession Hook',     category: 'Curiosity',  isPremium: false, description: 'Opens with a candid admission that earns trust',  template: 'I have to be honest about something I got wrong for years.',                    example: 'I have to be honest about something I got wrong for the first 4 years of my career.' },
  { id: 'plot-twist',         label: 'Plot Twist',          category: 'Curiosity',  isPremium: true,  description: 'Sets up one expectation then flips it',          template: 'Everyone told me [X]. What actually happened was [Y].',                          example: 'Everyone told me bootstrapping in India was impossible. What actually happened shocked me.' },
  { id: 'behind-the-curtain', label: 'Behind the Curtain',  category: 'Curiosity',  isPremium: true,  description: 'Promises a look at hidden processes',            template: 'Here is what actually happens behind the scenes at [type of company/event].',   example: 'Here is what actually happens behind the scenes at a top-tier VC pitch in India.' },
  { id: 'what-nobody-says',   label: 'What Nobody Says',    category: 'Curiosity',  isPremium: true,  description: 'Claims to share the unsaid truth',               template: 'What nobody says out loud about [topic] in [industry/country]...',              example: 'What nobody says out loud about the Indian tech hiring market right now...' },
  { id: 'uncomfortable-truth',label: 'Uncomfortable Truth', category: 'Curiosity',  isPremium: true,  description: 'States a truth the audience knows but avoids',   template: 'Here is an uncomfortable truth about [X] that we all know but won\'t say.',    example: 'Here is an uncomfortable truth about Indian startup culture that we all know but won\'t say.' },
  { id: 'hidden-cost',        label: 'Hidden Cost',         category: 'Curiosity',  isPremium: true,  description: 'Reveals an unexpected downside to a popular thing',template: 'The hidden cost of [popular choice/strategy] that nobody warns you about.',     example: 'The hidden cost of raising venture capital that nobody warns Indian founders about.' },
  { id: 'five-words',         label: 'Five Words',          category: 'Curiosity',  isPremium: true,  description: 'Ultra-short cryptic opener that demands context', template: '[Five words that create intrigue.] Let me explain.',                             example: 'We almost lost everything. Let me explain.' },
  { id: 'i-was-wrong',        label: 'I Was Wrong',         category: 'Curiosity',  isPremium: true,  description: 'Opens with a specific mistake admission',        template: 'I was completely wrong about [X]. Here is what I learned.',                     example: 'I was completely wrong about how Indian B2B sales actually works. Here is what I learned.' },
  { id: 'the-question-nobody-asks', label: 'The Unasked Question', category: 'Curiosity', isPremium: true, description: 'Raises the question everyone thinks but doesn\'t voice', template: 'Why does nobody ask [obvious question] about [industry topic]?', example: 'Why does nobody ask whether Indian startup valuations actually make sense anymore?' },

  // ── VALUE (20) ────────────────────────────────────────────────────────────

  { id: 'number-hook',        label: 'Number Hook',         category: 'Value',      isPremium: false, description: 'Leads with a specific number or stat',           template: '[Number] [result/insight] I learned in [time period]',                         example: '7 things I learned growing from 0 to ₹1 crore ARR in 18 months' },
  { id: 'how-to',             label: 'How-To',              category: 'Value',      isPremium: false, description: 'Promises a clear outcome or skill',              template: 'How to [achieve result] without [common obstacle]',                             example: 'How to get your first 5 SaaS customers without running a single ad' },
  { id: 'resource',           label: 'Resource Drop',       category: 'Value',      isPremium: false, description: 'Promises a curated list or toolkit',             template: '[Number] [tools/books/resources] that changed how I [do X]',                   example: '5 free tools that cut my content creation time in half' },
  { id: 'step-by-step',       label: 'Step-by-Step',        category: 'Value',      isPremium: false, description: 'Promises a clear sequential process',            template: 'Step-by-step: how I [achieved X] in [timeframe].',                              example: 'Step-by-step: how I took Razorpay from prospect to signed contract in 11 days.' },
  { id: 'quick-win',          label: 'Quick Win',           category: 'Value',      isPremium: false, description: 'Promises fast, actionable value',                template: 'One [change/habit/tweak] that improved [metric] by [amount] immediately.',      example: 'One email tweak that improved my reply rate by 40% immediately.' },
  { id: 'framework-hook',     label: 'Framework Hook',      category: 'Value',      isPremium: false, description: 'Introduces a named model or system',             template: 'The [Name] framework: how I [achieved X].',                                     example: 'The 3-2-1 framework: how I plan a month of LinkedIn content in 90 minutes.' },
  { id: 'mistakes-list',      label: 'Mistakes List',       category: 'Value',      isPremium: false, description: 'Lists common errors readers should avoid',       template: '[Number] mistakes [audience] make with [topic] — and how to fix them.',        example: '5 mistakes Indian founders make when pitching to angels — and how to fix them.' },
  { id: 'comparison-hook',    label: 'Comparison Hook',     category: 'Value',      isPremium: false, description: 'Contrasts two approaches to reveal the winner',  template: 'Most [people] do [X]. Top performers do [Y].',                                  example: 'Most founders chase press coverage. Top founders chase customer testimonials.' },
  { id: 'steal-this',         label: 'Steal This',          category: 'Value',      isPremium: false, description: 'Invites the reader to copy a working system',    template: 'Steal my [system/template/process] for [achieving X].',                         example: 'Steal my system for turning one LinkedIn post into 5 pieces of content.' },
  { id: 'pro-tip',            label: 'Pro Tip',             category: 'Value',      isPremium: false, description: 'Delivers a single high-value insider tip',       template: 'Pro tip for [audience]: [specific actionable advice].',                         example: 'Pro tip for Indian SDRs: never send a follow-up without adding one new piece of value.' },
  { id: 'save-this',          label: 'Save This',           category: 'Value',      isPremium: false, description: 'Explicitly tells reader to bookmark for later',  template: 'Save this for later: [what the post delivers].',                                example: 'Save this for later: my complete checklist for a LinkedIn profile that converts.' },
  { id: 'data-insight',       label: 'Data Insight',        category: 'Value',      isPremium: false, description: 'Leads with data and unpacks its meaning',        template: 'I analysed [N] [things] and found [surprising insight].',                       example: 'I analysed 200 cold emails sent to Indian CTOs and found one pattern that drove 80% of replies.' },
  { id: 'cheat-sheet',        label: 'Cheat Sheet',         category: 'Value',      isPremium: true,  description: 'Promises a dense reference in a short post',     template: 'My [topic] cheat sheet — everything I wish I had known when starting.',         example: 'My LinkedIn growth cheat sheet — everything I wish I had known in 2021.' },
  { id: 'formula-hook',       label: 'Formula Hook',        category: 'Value',      isPremium: true,  description: 'Shares a repeatable formula or equation',        template: 'The formula I use for [outcome]: [simple equation or pattern].',                example: 'The formula I use for every sales call: Listen 70%, speak 30%, always end with one question.' },
  { id: 'benchmark',          label: 'Benchmark Hook',      category: 'Value',      isPremium: true,  description: 'Gives readers a standard to measure themselves', template: 'Here is what [good/great/best-in-class] looks like for [metric] in [niche].',   example: 'Here is what good looks like for CAC in Indian B2B SaaS at seed stage.' },
  { id: 'roi-hook',           label: 'ROI Hook',            category: 'Value',      isPremium: true,  description: 'Quantifies the exact return on an action',       template: '[X hours/rupees/effort] invested → [specific measurable result].',              example: '3 hours per week on LinkedIn → ₹18L in inbound pipeline last quarter.' },
  { id: 'template-hook',      label: 'Template Hook',       category: 'Value',      isPremium: true,  description: 'Gives a ready-to-use template',                  template: 'Copy-paste this [template/script/email] that got me [result].',                 example: 'Copy-paste this cold email that got me a meeting with the Zepto founding team.' },
  { id: 'ultimate-guide',     label: 'Ultimate Guide',      category: 'Value',      isPremium: true,  description: 'Promises a comprehensive reference on a topic',  template: 'The ultimate guide to [topic] for [Indian/niche] professionals.',               example: 'The ultimate guide to negotiating your first senior role in Indian tech.' },
  { id: 'swipe-file',         label: 'Swipe File',          category: 'Value',      isPremium: true,  description: 'Curates examples worth copying',                 template: '[Number] [examples/phrases/emails] worth saving and using.',                   example: '8 subject lines worth saving — every one of these got a >40% open rate.' },
  { id: 'research-finding',   label: 'Research Finding',    category: 'Value',      isPremium: true,  description: 'Shares an original research insight',            template: 'I spent [time] researching [topic]. Here is the most important finding.',       example: 'I spent 3 months studying 50 Indian unicorn origin stories. Here is the most important finding.' },

  // ── STORY (20) ────────────────────────────────────────────────────────────

  { id: 'failure-story',      label: 'Failure Story',       category: 'Story',      isPremium: false, description: 'Opens with a candid failure',                   template: 'I failed at [X]. Here is exactly what went wrong and what I learned.',         example: 'I failed to close a ₹50L deal last quarter. Here is exactly what went wrong.' },
  { id: 'before-after',       label: 'Before & After',      category: 'Story',      isPremium: false, description: 'Shows a dramatic transformation',               template: '[Time ago]: [bad state]. Today: [good state]. Here is what changed.',          example: '12 months ago I had zero LinkedIn followers. Today I get 20 inbound leads a week. Here is what changed.' },
  { id: 'moment-hook',        label: 'The Moment',          category: 'Story',      isPremium: false, description: 'Drops the reader into a single vivid moment',    template: 'The day [specific event happened] changed everything for me.',                  example: 'The day my co-founder quit two months before our Series A changed everything for me.' },
  { id: 'humble-beginning',   label: 'Humble Beginning',    category: 'Story',      isPremium: false, description: 'Starts with an honest origin story',            template: '[Time ago], I [humble starting point]. Today, [current achievement].',         example: '5 years ago, I was rejected from every IIM. Today I run a ₹12 crore bootstrapped business.' },
  { id: 'pivot-moment',       label: 'Pivot Moment',        category: 'Story',      isPremium: false, description: 'Describes the decision that changed direction',  template: 'I made a decision [time ago] that changed the entire trajectory of my career.',  example: 'I made a decision in 2020 that changed the entire trajectory of my career.' },
  { id: 'crisis-point',       label: 'Crisis Point',        category: 'Story',      isPremium: false, description: 'Opens at the moment of highest pressure',        template: 'We had [X days/hours] left and [critical thing] had just gone wrong.',          example: 'We had 11 days of runway left and our lead investor had just pulled out.' },
  { id: 'unexpected-win',     label: 'Unexpected Win',      category: 'Story',      isPremium: false, description: 'Shares a win that came from an unlikely source',  template: 'My biggest [result] came from the thing I almost did not try.',                 example: 'My biggest client this year came from a LinkedIn comment I almost did not leave.' },
  { id: 'rejection-hook',     label: 'Rejection Hook',      category: 'Story',      isPremium: false, description: 'Leads with a rejection that became a catalyst',  template: 'I was rejected from [X]. It turned out to be the best thing that ever happened.',example: 'I was rejected from Sequoia\'s accelerator in 2021. It turned out to be the best thing that ever happened.' },
  { id: 'mistake-that-cost',  label: 'Costly Mistake',      category: 'Story',      isPremium: false, description: 'Shares a specific mistake with a real cost',     template: 'One decision cost us [₹/time/clients]. Here is what I would do differently.',   example: 'One hiring decision cost us ₹35L and 6 months of momentum. Here is what I would do differently.' },
  { id: 'first-client',       label: 'First Client Story',  category: 'Story',      isPremium: false, description: 'Tells the story of landing the first customer',  template: 'Here is the story of how we landed our first paying customer.',                  example: 'Here is the story of how we landed our first ₹1L/month retainer with zero marketing budget.' },
  { id: 'viral-moment',       label: 'Viral Moment',        category: 'Story',      isPremium: false, description: 'Shares a moment of unexpected public attention',  template: 'One [post/tweet/decision] changed how [number] people see me.',                 example: 'One LinkedIn post changed how 40,000 people in Indian tech see my company.' },
  { id: 'mentor-lesson',      label: 'Mentor Lesson',       category: 'Story',      isPremium: false, description: 'Passes on wisdom received from a mentor',        template: 'The best advice I ever got came from [mentor type] who told me [advice].',       example: 'The best advice I ever got came from my first manager at TCS who told me one thing.' },
  { id: 'comeback-story',     label: 'Comeback Story',      category: 'Story',      isPremium: true,  description: 'Documents a recovery from a low point',          template: 'A year ago, [low point]. Today, [high point]. Here is how.',                    example: 'A year ago, our startup was 3 weeks from shutting down. Today we are at ₹2Cr ARR. Here is how.' },
  { id: 'team-story',         label: 'Team Story',          category: 'Story',      isPremium: true,  description: 'Tells a story that celebrates the team',         template: '[Team member] did something this week that reminded me why this company exists.', example: 'Our junior developer did something this week that reminded me why this company exists.' },
  { id: 'customer-story',     label: 'Customer Story',      category: 'Story',      isPremium: true,  description: 'Tells a specific customer transformation story', template: '[Customer type] came to us with [problem]. [Time] later, [result].',             example: 'A Pune-based D2C founder came to us with ₹0 in organic traffic. 90 days later, 40k monthly visitors.' },
  { id: 'risk-taken',         label: 'Risk Taken',          category: 'Story',      isPremium: true,  description: 'Describes a bold bet and its outcome',           template: 'I took a risk that most people called stupid. Here is what happened.',           example: 'I quit my Infosys job without another offer in hand. Here is what happened in the next 12 months.' },
  { id: 'fear-faced',         label: 'Fear Faced',          category: 'Story',      isPremium: true,  description: 'Documents overcoming a specific professional fear',template: 'I was terrified of [X]. The day I finally did it, everything changed.',          example: 'I was terrified of public speaking. The day I finally did it, everything changed.' },
  { id: 'year-in-review',     label: 'Year in Review',      category: 'Story',      isPremium: true,  description: 'Reflects on a year\'s worth of growth',          template: '[Year]: [number of things] that changed how I [think/work/lead].',              example: '2024: 7 things that permanently changed how I think about building in India.' },
  { id: 'decade-lesson',      label: 'Decade Lesson',       category: 'Story',      isPremium: true,  description: 'Extracts lessons from a long span of time',      template: '[Number] years in [field]. Here is what I know now that I wish I knew then.',   example: '10 years in Indian SaaS sales. Here is what I know now that I wish I knew then.' },
  { id: 'competition-story',  label: 'Competition Story',   category: 'Story',      isPremium: true,  description: 'Shares a story of competing and what it taught', template: 'We went up against [well-known competitor]. Here is what we learned.',           example: 'We went up against a well-funded Mumbai startup for the same enterprise contract. Here is what we learned.' },

  // ── ENGAGEMENT (20) ───────────────────────────────────────────────────────

  { id: 'bold-claim',         label: 'Bold Claim',          category: 'Engagement', isPremium: false, description: 'Opens with a confident, defensible statement',   template: '[Bold declarative statement about your niche]',                                 example: 'LinkedIn reach is dead — unless you do this one thing differently.' },
  { id: 'direct-question',    label: 'Direct Question',     category: 'Engagement', isPremium: false, description: 'Poses a question the reader wants answered',     template: '[Specific question your ideal reader is asking themselves]',                    example: 'Are you wasting your best content ideas by posting them at the wrong time?' },
  { id: 'hot-take',           label: 'Hot Take',            category: 'Engagement', isPremium: false, description: 'Delivers one sharp, defensible opinion',          template: 'Hot take: [specific, polarising opinion about your niche].',                    example: 'Hot take: most Indian startup founders are optimising for funding, not for building.' },
  { id: 'poll-question',      label: 'Poll Question',       category: 'Engagement', isPremium: false, description: 'Sets up a LinkedIn poll for maximum reach',       template: 'Quick question for my network: [binary or multi-choice question]?',            example: 'Quick question for my network: what stops you most from posting on LinkedIn consistently?' },
  { id: 'debate-starter',     label: 'Debate Starter',      category: 'Engagement', isPremium: false, description: 'Invites two sides to make a case',                template: '[Position A] vs [Position B] — which side are you on?',                        example: 'Bootstrapped vs venture-backed — which path is right for Indian founders in 2025?' },
  { id: 'agree-or-disagree',  label: 'Agree or Disagree',   category: 'Engagement', isPremium: false, description: 'States a position and asks readers to take a side',template: 'Agree or disagree: [specific statement about your industry].',                  example: 'Agree or disagree: most Indian companies are terrible at retaining their best engineers.' },
  { id: 'community-question', label: 'Community Question',  category: 'Engagement', isPremium: false, description: 'Asks the audience for their experience',          template: 'What is your experience with [topic]? I am curious.',                           example: 'What is your experience with salary negotiations in Indian tech? I am genuinely curious.' },
  { id: 'this-or-that',       label: 'This or That',        category: 'Engagement', isPremium: false, description: 'Forces a binary preference choice',               template: '[Option A] or [Option B]? How do you decide?',                                  example: 'Speed or quality? How do Indian product teams actually decide when deadlines hit?' },
  { id: 'open-question',      label: 'Open Question',       category: 'Engagement', isPremium: false, description: 'Asks a broad, reflective question',              template: 'What is the single best [lesson/tool/advice] you have found for [topic]?',     example: 'What is the single best productivity habit you have found that actually works long-term?' },
  { id: 'hypothetical',       label: 'Hypothetical',        category: 'Engagement', isPremium: false, description: 'Poses a what-if scenario to spark imagination',   template: 'If you could [change one thing] about [industry/role/niche], what would it be?',example: 'If you could change one thing about how Indian companies hire, what would it be?' },
  { id: 'prediction-hook',    label: 'Prediction Hook',     category: 'Engagement', isPremium: false, description: 'Makes a specific, time-bound industry prediction', template: 'My prediction for [industry] in [timeframe]: [specific call].',                  example: 'My prediction for Indian SaaS in the next 18 months: consolidation, not growth.' },
  { id: 'industry-pulse',     label: 'Industry Pulse',      category: 'Engagement', isPremium: false, description: 'Checks what the audience is seeing in the market', template: 'What are you seeing in [industry] right now? I am noticing [observation].',      example: 'What are you seeing in Indian tech hiring right now? I am noticing something interesting.' },
  { id: 'social-proof',       label: 'Social Proof Hook',   category: 'Engagement', isPremium: true,  description: 'Opens with a result that proves credibility',     template: 'We [achieved X result] in [timeframe]. Here is the exact playbook.',           example: 'We closed ₹40L in new business in 90 days with zero paid ads. Here is the exact playbook.' },
  { id: 'challenge-hook',     label: 'Challenge Hook',       category: 'Engagement', isPremium: true, description: 'Invites readers to try something with you',       template: 'I am challenging myself to [X] for [N days]. Who is joining me?',              example: 'I am challenging myself to write 30 LinkedIn posts in 30 days. Who is joining me?' },
  { id: 'finish-this-sentence',label: 'Finish This Sentence',category: 'Engagement', isPremium: true, description: 'Drives comments with sentence completion',        template: 'Finish this sentence: The best thing about working in [niche] is ____.',        example: 'Finish this sentence: The best thing about working in Indian startups is ____.' },
  { id: 'myth-vs-truth',      label: 'Myth vs Truth',       category: 'Engagement', isPremium: true,  description: 'Structures a post around common misconceptions',  template: 'What people think [X] looks like vs what it actually looks like.',              example: 'What people think a funded Indian startup looks like vs what it actually looks like.' },
  { id: 'your-take',          label: 'Your Take',           category: 'Engagement', isPremium: true,  description: 'Shares own view then invites reader\'s perspective',template: 'Here is my take on [topic]. I want to know yours.',                             example: 'Here is my take on remote work in Indian companies. I want to know yours.' },
  { id: 'controversy-hook',   label: 'Controversy Hook',    category: 'Engagement', isPremium: true,  description: 'Addresses a divisive topic directly',             template: 'Let us talk about the thing dividing [your industry/niche] right now.',         example: 'Let us talk about the thing dividing Indian tech right now: return-to-office mandates.' },
  { id: 'call-to-action-hook',label: 'CTA Hook',            category: 'Engagement', isPremium: true,  description: 'Leads with the desired reader action upfront',    template: 'If you are a [audience] who wants [outcome], read this post.',                  example: 'If you are a first-time founder in India who wants to close your first B2B deal, read this post.' },
  { id: 'tag-someone',        label: 'Tag Someone',         category: 'Engagement', isPremium: true,  description: 'Prompts tagging to expand reach organically',     template: 'Tag someone who needs to hear this about [topic].',                             example: 'Tag a founder who needs to hear this about fundraising in India right now.' },

  // ── URGENCY (18) ──────────────────────────────────────────────────────────

  { id: 'trend-hook',         label: 'Trend Hook',          category: 'Urgency',    isPremium: false, description: 'Ties into something happening right now',        template: 'What [current trend/event] means for [your niche] — and what to do next',      example: 'What the AI coding wave means for Indian software engineers — and what to do next' },
  { id: 'warning',            label: 'Warning Hook',        category: 'Urgency',    isPremium: false, description: 'Warns about a mistake or coming change',         template: 'If you are still doing [X], stop. Here is why this is hurting you.',           example: 'If you are still sending cold connection requests with no message, stop. Here is why this is killing your pipeline.' },
  { id: 'industry-shift',     label: 'Industry Shift',      category: 'Urgency',    isPremium: false, description: 'Describes a change reshaping the industry',      template: '[Industry] is changing faster than most people realise. Here is what I am seeing.',example: 'Indian B2B sales is changing faster than most people realise. Here is what I am seeing.' },
  { id: 'market-change',      label: 'Market Change',       category: 'Urgency',    isPremium: false, description: 'Highlights a market shift with real implications', template: 'Something shifted in [market] this [month/quarter]. Here is what it means.',    example: 'Something shifted in the Indian SaaS hiring market this quarter. Here is what it means.' },
  { id: 'breaking-news',      label: 'Breaking News',       category: 'Urgency',    isPremium: false, description: 'Reacts to a timely industry development',        template: '[News/development] just happened. Here is what it means for [your audience].',  example: 'SEBI just changed the rules for startup ESOPs. Here is what it means for Indian founders.' },
  { id: 'now-or-never',       label: 'Now or Never',        category: 'Urgency',    isPremium: false, description: 'Frames the current moment as a rare window',     template: 'There is a narrow window right now for [audience] to [opportunity]. Here is why.',example: 'There is a narrow window right now for Indian B2B founders to land enterprise pilots. Here is why.' },
  { id: 'before-too-late',    label: 'Before It\'s Too Late',category: 'Urgency',   isPremium: false, description: 'Warns of a closing opportunity or coming problem', template: 'Do [X] now — before [coming change/deadline] makes it much harder.',             example: 'Build your LinkedIn audience now — before algorithm changes make organic reach impossible.' },
  { id: 'time-sensitive',     label: 'Time-Sensitive',      category: 'Urgency',    isPremium: false, description: 'Creates genuine urgency around a timely insight',  template: 'This [opportunity/threat] is only relevant for the next [timeframe].',          example: 'This hiring market shift is only relevant for the next 60 days — then the window closes.' },
  { id: 'expiring-soon',      label: 'Expiring Soon',       category: 'Urgency',    isPremium: false, description: 'Flags something that won\'t last',               template: '[Opportunity/window/trend] will not last. Here is how to use it now.',          example: 'Organic LinkedIn reach for Indian creators will not last. Here is how to use it now.' },
  { id: 'early-adopter',      label: 'Early Adopter',       category: 'Urgency',    isPremium: false, description: 'Positions reader to move before the crowd',      template: 'Most [audience] have not noticed [X] yet. Early movers will win.',              example: 'Most Indian marketers have not noticed this AI workflow yet. Early movers will win.' },
  { id: 'act-now',            label: 'Act Now',             category: 'Urgency',    isPremium: true,  description: 'Gives a direct call to move immediately',        template: 'Stop waiting for the perfect time to [X]. The best time is now. Here is why.',  example: 'Stop waiting for the perfect time to start posting on LinkedIn. The best time is now. Here is why.' },
  { id: 'deadline-hook',      label: 'Deadline Hook',       category: 'Urgency',    isPremium: true,  description: 'Anchors urgency to a specific real deadline',    template: 'You have [N days/weeks] left to take advantage of [opportunity].',              example: 'You have roughly 90 days left to take advantage of the current Indian AI hiring surge.' },
  { id: 'dont-miss',          label: 'Don\'t Miss',         category: 'Urgency',    isPremium: true,  description: 'Flags something the reader risks overlooking',   template: 'Do not miss what is happening in [niche] right now.',                           example: 'Do not miss what is happening in Indian founder communities right now — it is a shift.' },
  { id: 'last-chance',        label: 'Last Chance',         category: 'Urgency',    isPremium: true,  description: 'Creates scarcity around a fading opportunity',   template: 'This is likely the last time [opportunity] will be this accessible.',           example: 'This is likely the last time bootstrapped Indian SaaS can compete with VC-backed players on talent.' },
  { id: 'disruption-hook',    label: 'Disruption Hook',     category: 'Urgency',    isPremium: true,  description: 'Names a force that is disrupting the status quo', template: '[Technology/trend] is disrupting [industry]. Here is who wins and who loses.',   example: 'AI is disrupting Indian IT services. Here is who wins and who loses in the next 3 years.' },
  { id: 'wake-up-call',       label: 'Wake-Up Call',        category: 'Urgency',    isPremium: true,  description: 'Jolts the audience out of complacency',          template: 'A wake-up call for [audience]: [uncomfortable reality] is happening right now.',  example: 'A wake-up call for Indian product managers: your role is being redefined right now.' },
  { id: 'window-closing',     label: 'Window Closing',      category: 'Urgency',    isPremium: true,  description: 'Describes a narrowing opportunity window',       template: 'The window for [opportunity] is closing faster than anyone expected.',           example: 'The window for affordable tech talent in India is closing faster than anyone expected.' },
  { id: 'first-mover',        label: 'First Mover',         category: 'Urgency',    isPremium: true,  description: 'Rewards early movers with insider knowledge',    template: 'First movers in [space] right now will have an unfair advantage in [timeframe].', example: 'First movers in AI-native Indian B2B tools right now will have an unfair advantage in 2026.' },

  // ── AUTHORITY (15) ────────────────────────────────────────────────────────

  { id: 'years-experience',   label: 'Years of Experience', category: 'Authority',  isPremium: true,  description: 'Establishes credibility through tenure',         template: 'After [N] years of [doing X], here is what I know.',                            example: 'After 12 years of enterprise sales in India, here is what I know about closing large deals.' },
  { id: 'case-study-hook',    label: 'Case Study Hook',     category: 'Authority',  isPremium: true,  description: 'Leads with a named result as proof of method',   template: 'Case study: how [client type] achieved [specific result] with [approach].',     example: 'Case study: how a Bengaluru SaaS company grew ARR 3x in 8 months by changing one thing.' },
  { id: 'client-result',      label: 'Client Result',       category: 'Authority',  isPremium: true,  description: 'Shows a specific measurable client outcome',     template: 'Client result: [before state] → [after state] in [timeframe].',                 example: 'Client result: ₹0 in LinkedIn pipeline → ₹22L in qualified inbound in 6 months.' },
  { id: 'track-record',       label: 'Track Record',        category: 'Authority',  isPremium: true,  description: 'Summarises a history of consistent results',     template: '[N clients/companies/years], [consistent result]. Here is how.',               example: '40 clients, every single one grew their LinkedIn pipeline in 90 days. Here is how.' },
  { id: 'expert-quote',       label: 'Expert Quote',        category: 'Authority',  isPremium: true,  description: 'Opens with a powerful quote from a respected source',template: '"[Exact quote]" — [name, role]. Here is why this changed how I work.',          example: '"Distribution eats product for breakfast." — a top Indian VC told me this. Here is why it changed everything.' },
  { id: 'published-research', label: 'Published Research',  category: 'Authority',  isPremium: true,  description: 'Cites original or curated research',             template: 'New research shows [finding]. Here is what it means for [your audience].',       example: 'New research from IIM Ahmedabad shows high-performing teams share one unexpected trait.' },
  { id: 'award-recognition',  label: 'Award Recognition',   category: 'Authority',  isPremium: true,  description: 'Shares recognition while keeping focus on lesson', template: 'We were [recognised/awarded] for [X]. Here is what actually made it happen.',   example: 'We were named one of India\'s top 25 startups to watch. Here is what actually made it happen.' },
  { id: 'media-mention',      label: 'Media Mention',       category: 'Authority',  isPremium: true,  description: 'Uses press coverage as social proof',             template: 'After being featured in [publication], one insight I could not share publicly...',example: 'After being featured in The Ken last month, one insight I could not share publicly...' },
  { id: 'speaker-hook',       label: 'Speaker Hook',        category: 'Authority',  isPremium: true,  description: 'Leverages a speaking engagement for credibility',  template: 'I spoke at [event] last week. Here is the one thing I told [audience].',        example: 'I spoke at SaaS Insider India last week. Here is the one thing I told 400 founders.' },
  { id: 'vip-access',         label: 'VIP Access',          category: 'Authority',  isPremium: true,  description: 'Shares a perspective from a high-access position',template: 'I spent [time] with [high-status group]. Here is what they are all focused on.',  example: 'I spent a day with a room of top Indian founders last week. Here is what they are all focused on.' },
  { id: 'exclusive-insight',  label: 'Exclusive Insight',   category: 'Authority',  isPremium: true,  description: 'Shares information not publicly available',      template: 'I cannot share the source, but here is something you need to know about [topic].',example: 'I cannot share the source, but here is something Indian SaaS founders need to know right now.' },
  { id: 'investor-lens',      label: 'Investor Lens',       category: 'Authority',  isPremium: true,  description: 'Provides an investor-level perspective on a topic', template: 'As someone who has seen [N] pitch decks, here is what separates the ones that close.',example: 'As someone who has reviewed 200+ Indian startup pitch decks, here is what separates the ones that close.' },
  { id: 'ceo-perspective',    label: 'CEO Perspective',     category: 'Authority',  isPremium: true,  description: 'Shares a founder or executive-level view',       template: 'Running [company type] has taught me [number] things about [topic].',           example: 'Running a bootstrapped Indian SaaS for 6 years has taught me 5 things about resilience.' },
  { id: 'board-insight',      label: 'Board Insight',       category: 'Authority',  isPremium: true,  description: 'Shares a lesson from high-level strategic discussions',template: 'The question my board asked that completely changed how I think about [X].',      example: 'The question my board asked last quarter completely changed how I think about product-market fit.' },
  { id: 'nda-secret',         label: 'NDA Secret',          category: 'Authority',  isPremium: true,  description: 'Teases insider knowledge safely within legal bounds',template: 'I cannot name the company, but I can tell you what they did differently.',       example: 'I cannot name the company, but I can tell you what this top Indian startup did differently to 10x revenue.' },
]
